version: '3'

services:
  app:
    build: ./
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - "3000:3000"
